name: CI
on: [push, pull_request]

jobs:
  test-book:
    name: Test Book
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
    - name: Install latest mdbook
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir bin
        curl -sSL $url | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH
    - name: Build Dependencies
      run: cargo build
    - name: Test Book
      run: CARGO_MANIFEST_DIR=`pwd` mdbook test bevy-workshop -L target/debug/deps

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup toolchain install stable
        rustup default stable
    - name: Clippy
      run: cargo clippy

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup toolchain install stable
        rustup default stable
    - name: Format
      run: cargo fmt -- --check
